articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    # ex: /articles/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:article_id>/comment/', views.comment, name='comment')
    # # ex: /articles/5/results/
    # path('<int:question_id>/results/', views.results, name='results'),
]

blog/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import include,  path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('', include('articles.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

articles/models.py
import datetime

from django.db import models
from django.utils import timezone


class Article(models.Model):
    title = models.CharField(verbose_name='Заголовок статьи', max_length=200)
    text = models.TextField(verbose_name='Текст статьи')
    pub_date = models.DateTimeField('Дата публикации')

    def __str__(self):
        return self.title

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    def get_last_comments(self):
        return self.comment_set.order_by('-created_date')[:10]

    def get_comments_count(self):
        return self.comment_set.count()


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    author = models.CharField('Автор комментирия', max_length=50)
    text = models.CharField(verbose_name='Текст комментирия', max_length=300)
    created_date = models.DateTimeField('Дата создания')

    def __str__(self):
        return self.author

articles/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Article, Comment


class IndexView(generic.ListView):
    template_name = 'articles/index.html'
    context_object_name = 'latest_article_list'
    queryset = Article.objects.filter(
        pub_date__lte=timezone.now()).order_by('-pub_date')[:5]
    paginate_by = 10

    # def get_queryset(self):
    #     """Return the last five published articles."""
    #     return Article.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Article
    template_name = 'articles/detail.html'


# def detail(request, article_id):
#     article = get_object_or_404(Article, pk=article_id)
#     return render(request, 'detail.html', {'article': article})


# def results(request, article_id):
#     question = get_object_or_404(Article, pk=article_id)
#     return render(request, 'results.html', {'article': article})


def comment(request, article_id):
    article = get_object_or_404(Article, pk=article_id)
    article.comment_set.create(
        author=request.POST['author'], text=request.POST['comment_text'], created_date=timezone.now())
    article.save()
    return HttpResponseRedirect(reverse('detail', args=(article.id,)))

articles/templates/detail.html
<h1>{{ article.title }}</h1>
<p> {{ article.text }}</p>

<hr>

<h3>Добавить комментарий</h3>

<form action="{% url 'comment' article.id %}" method="post">
	{% csrf_token %}
	<input type="text" name="author">
	<input type="text" name="comment_text">
	<input type="submit" value="Сохранить">
</form>

<ul>
{% for comment in article.last_comments %}
    <li>
		<span>{{ comment.author }}</span>
		<p>
		{{ comment.text }}
		</p>
		</li>
		<hr>
{% endfor %}
</ul>

templates/articles/detail.html
{% extends "base_generic.html" %}

{% block content %}

<div class="card">
  <div class="card-header">
    <h2>{{ article.title }}</h2>
  </div>
  <div class="card-body">
    <p>{{ article.text }}</p>
  </div>
  <div class="card-footer text-left">
    <a class="btn btn-link" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
			Add comment
		</a>
		<div class="collapse" id="collapseExample">
			<div class="card card-body">
			<form action="{% url 'articles:comment' article.id %}" method="post">
				{% csrf_token %}
				<div class="form-group">
					<label for="author">Author</label>
					<input type="text" class="form-control" id="author" name="author" placeholder="Author">
				</div>
				<div class="form-group">
					<label for="comment_text">Comment...</label>
					<input type="text" class="form-control" id="comment_text" name="comment_text" placeholder="Comment...">
				</div>
				<div  class="text-right">
					<input class="btn btn-success" type="submit" value="Save">
				</div>
			</form>
			</div>
		</div>
  </div>
</div>








<ul>
{% for comment in article.get_last_comments %}
    <li>
		<span>{{ comment.author }}</span>
		<p>
		{{ comment.text }}
		</p>
		</li>
		<hr>
{% endfor %}
</ul>
{% endblock content %}

templates/articles/index.html
{% extends "base_generic.html" %}

{% block content %}
	{% if latest_article_list %}
			{% for article in latest_article_list %}
					<div class="card mb-2 shadow-sm">
						<div class="card-body">
							<h4 class="card-title">{{ article.title }}</h4>
							<p class="card-text mt-2">{{ article.text|slice:":300" }}...</p>
							<a href="{% url 'articles:detail' article.id %}" class="btn btn-info stretched-link">Detail</a>
							<div class="pt-2">
								<small class="text-muted">Comments: {{article.get_comments_count}}</small>
								<small class="text-muted">Public date: {{article.pub_date}}</small>
							</div>
					</div>
				</div>
			{% endfor %}
	{% else %}
			<p>No polls are available.</p>
	{% endif %}


	{% block pagination %}
		{% if is_paginated %}
			<div class="p-2">		
				{% if page_obj.has_previous %}
					<a href="{{ request.path }}?page={{ page_obj.previous_page_number }}" class="btn btn-outline-secondary">back</a>
				{% else %}
					<a href="" class="btn btn-light disabled">back</a>
				{% endif %}
				{% if page_obj.has_next %}
					<a href="{{ request.path }}?page={{ page_obj.next_page_number }}" class="btn btn-outline-secondary">next</a>
				{% else %}
					<a href="" class="btn btn-light disabled">next</a>
				{% endif %}
			</div>
		{% endif %}
	{% endblock pagination %} 
{% endblock %}

templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  
  {% block title %}<title>Software Developer's blog</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  
  <!-- Добавление дополнительного статического CSS файла -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
  <div class="container-fluid">
		
    <div class="row p-4">
      <div class="col-sm-2">
				{% block left_sidebar %}
				<div class="card border-0">
						<img src="{% static "images/logo2.jpg" %}" class="card-img-top d-block m-auto" alt="logo">
					<div class="card-body">
						<h2 class="card-title">Tech Crutch</h2>
						<p class="card-text">Everything is possible. Power of legacy code.</p>
					</div>
					<ul class="list-group list-group-flush">
						<a href="{% url 'articles:index' %}"><li class="list-group-item">Home</li></a>
						<a href="{% url 'admin:index' %}"><li class="list-group-item">Admin pane</li></a>
						<a href="{% url 'articles:index' %}" ><li class="list-group-item">Articles</li></a>
					</ul>
					<div class="card-body">
						2020 (c) Secured by Tech Crutch
					</div>
				</div>

				{% endblock left_sidebar %}
      </div>
      <div class="col-sm-8 pl-4 pr-4">
      {% block content %}{% endblock %}
      </div>
			<div class="col-sm-2">
				{% block right_sidebar %}
					<input class="form-control" type="text" placeholder="Search">
					<div class="card mt-2 border-0">
						<div class="card-body">
							<h5 class="card-title">About me</h5>
							<h6 class="card-subtitle mb-2 text-muted">My name is Rybin Ivan</h6>
							<p class="card-text">This is my first Django web site.</p>
							<a href="#" class="card-link">Subscribe</a>
							<a href="#" class="card-link text-danger">Report</a>
						</div>
					</div>
				{% endblock right_sidebar %}
      </div>
    </div>

  </div>
	<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>